name: Build and Test
on:
  push:
    branches:
    - master
jobs:
  runner:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Package Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build Solution
        run:  dotnet build -c Release
      - name: Test Solution
        run:  dotnet test
      - name: GH Deploy Workaround
        run: |
           export REPO_NAME=$(echo ${GITHUB_REPOSITORY} | sed 's/stoiveyp\///')
           for f in ./${REPO_NAME}/bin/Release/Alexa.NET.Assertions*.nupkg
           do
             curl -vX PUT -u "stoiveyp:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/stoiveyp/
           done
        shell: bash
      - name: GH Deploy
        run: |
          export REPO_NAME=$(echo ${GITHUB_REPOSITORY} | sed 's/stoiveyp\///')
          dotnet nuget push ./${REPO_NAME}/bin/Release/Alexa.NET.Assertions*.nupkg --source "https://nuget.pkg.github.com/stoiveyp/index.json" --api-key stoiveyp:${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Deploy to NuGet
        run: |
          export REPO_NAME=$(echo ${GITHUB_REPOSITORY} | sed 's/stoiveyp\///')
          dotnet nuget push ./${REPO_NAME}/bin/Release/Alexa.NET.Assertions*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
